# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3736947383f8a75811b5ddb460782254d773a4f57661ce92b0be3832611fa4ab7f2faff4de879171cfb380d398ec53d4d75aab6630e5b2fdb2ec461c40972e6b

test:
  secret_key_base: e750edaa41fce175a785521ed28ff8314874474186eb67477e1bf87a1ddfad622273e0ea45339cc4514c66fd6c2885b7d0083d140ff1ae101f932fd785d16fa3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["5710f81f8e5389ee514fe825541b3c98ce2f69dde681906df08fd20727bfb0507e7473b8599e8d719956259c9952a617034c7f1346ef2051e60cb3b9393ee190"] %>
